[package]
name = "btc-tx-hex"
version = "0.1.0"
authors = ["448OG"]
edition = "2021"
license = "CC0-1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
